#!/bin/bash

echo -n "Enter a temperature in Fahrenheit -> "
read x
#records Fahrenheit temperautre input - decimal values allowed

x=`echo "scale=3; $x-32" | bc`
x=`echo "scale=1; $x*5/9" | bc`
#converts Fahrenheit to Celcius - output rounded down to nearest tenth of a degree

echo "Temperature equals $x degrees Celcius"
#output message
